[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/spa"

[context.production.environment]
  OPENAI_API_KEY = "YOUR_OPENAI_API_KEY"


[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
